---
abstract: 'Create and manipulate PAR distributions'
author:
  - 'Audrey Tang <cpan@audreyt.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.44, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PAR-Dist
no_index:
  directory:
    - t
    - inc
requires:
  File::Find: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Temp: '0'
resources:
  MailingList: mailto:par@perl.org
  bugtracker: https://rt.cpan.org/Dist/Display.html?Queue=PAR-Dist
  repository: git://github.com/rschupp/PAR-Dist.git
version: '0.51'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
